require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/rent_sessions", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # RentSession. As you add validations to RentSession, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      RentSession.create! valid_attributes
      get rent_sessions_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      rent_session = RentSession.create! valid_attributes
      get rent_session_url(rent_session)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_rent_session_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      rent_session = RentSession.create! valid_attributes
      get edit_rent_session_url(rent_session)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new RentSession" do
        expect {
          post rent_sessions_url, params: { rent_session: valid_attributes }
        }.to change(RentSession, :count).by(1)
      end

      it "redirects to the created rent_session" do
        post rent_sessions_url, params: { rent_session: valid_attributes }
        expect(response).to redirect_to(rent_session_url(RentSession.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new RentSession" do
        expect {
          post rent_sessions_url, params: { rent_session: invalid_attributes }
        }.to change(RentSession, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post rent_sessions_url, params: { rent_session: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested rent_session" do
        rent_session = RentSession.create! valid_attributes
        patch rent_session_url(rent_session), params: { rent_session: new_attributes }
        rent_session.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the rent_session" do
        rent_session = RentSession.create! valid_attributes
        patch rent_session_url(rent_session), params: { rent_session: new_attributes }
        rent_session.reload
        expect(response).to redirect_to(rent_session_url(rent_session))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        rent_session = RentSession.create! valid_attributes
        patch rent_session_url(rent_session), params: { rent_session: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested rent_session" do
      rent_session = RentSession.create! valid_attributes
      expect {
        delete rent_session_url(rent_session)
      }.to change(RentSession, :count).by(-1)
    end

    it "redirects to the rent_sessions list" do
      rent_session = RentSession.create! valid_attributes
      delete rent_session_url(rent_session)
      expect(response).to redirect_to(rent_sessions_url)
    end
  end
end
