require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/residents", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Resident. As you add validations to Resident, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Resident.create! valid_attributes
      get residents_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      resident = Resident.create! valid_attributes
      get resident_url(resident)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_resident_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      resident = Resident.create! valid_attributes
      get edit_resident_url(resident)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Resident" do
        expect {
          post residents_url, params: { resident: valid_attributes }
        }.to change(Resident, :count).by(1)
      end

      it "redirects to the created resident" do
        post residents_url, params: { resident: valid_attributes }
        expect(response).to redirect_to(resident_url(Resident.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Resident" do
        expect {
          post residents_url, params: { resident: invalid_attributes }
        }.to change(Resident, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post residents_url, params: { resident: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested resident" do
        resident = Resident.create! valid_attributes
        patch resident_url(resident), params: { resident: new_attributes }
        resident.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the resident" do
        resident = Resident.create! valid_attributes
        patch resident_url(resident), params: { resident: new_attributes }
        resident.reload
        expect(response).to redirect_to(resident_url(resident))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        resident = Resident.create! valid_attributes
        patch resident_url(resident), params: { resident: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested resident" do
      resident = Resident.create! valid_attributes
      expect {
        delete resident_url(resident)
      }.to change(Resident, :count).by(-1)
    end

    it "redirects to the residents list" do
      resident = Resident.create! valid_attributes
      delete resident_url(resident)
      expect(response).to redirect_to(residents_url)
    end
  end
end
